# @package runtime

modelname: bilateral_upsample_net
predict_illumination: false
loss: # when self_supervised is true, this option will be ignored.
  mse: 1.0
  cos: 0.1
  ltv: 0.1      # only matters when predict_illumination is true.

luma_bins: 8
channel_multiplier: 1
spatial_bin: 16
batch_norm: true
low_resolution: 256
coeffs_type: matrix    # selected from [matrix, gamma, retinex]

conv_type: conv

# choose from: [ori, hist-unet]
backbone: ori

# type: false or int.
# if N, do : illu_map **= N to adjust the brightness of the output.
illu_map_power: false

# only work when using hist-unet
defaults:
  - hist_unet.default@hist_unet
