# @package runtime

defaults:
  - lcdpnet.default

loss:
  ltv: 0              # ltv applied on the FINAL OUTPUT.
  cos: 0            # cos similarity loss
  cos2: 0.5            # cos with sigmoid
  tvloss1: 0       # tvloss applied on the illumination
  tvloss2: 0       # tvloss applied on the inverse illumination
  l1_loss: 1.0        # default pixel-wise l1 loss
  tvloss1_new: 0.01
  tvloss2_new: 0.01

backbone: bilateral_upsample_net

bilateral_upsample_net:
  backbone: hist-unet
  hist_unet:
    guide_feature_from_hist: true
    region_num: 2
    drconv_position: [ 0,1 ]
    channel_nums: [ 8,16,32,64,128 ]