# @package aug


# crop size:
#  - false for not cropping;
#  - int n for cropping square [n. n];
#  - [h, w] for cropping specific size/
crop: false


# downsample factor.
#  - value > 1 for downsample;
#  - 0.x for upsample;
#  - [h, w] for specific size;
#  - false for not resizing.
downsample: false

h-flip: false
v-flip: false

lightness_adjust: false
contrast_adjust: false

resize_divisible_n: false  # align input image size to the number divisible by N to avoid some size-mismatch error.